# Check how many event logs have activities with the same timestamp

In [2]:
from pm4py.objects.log.importer.xes import importer as xes_importer
from collections import defaultdict, Counter
import math
import os
import multiprocessing
from tqdm import tqdm

def compute_transition_entropy(traces):
    transitions = defaultdict(Counter)
    for trace in traces:
        events = [e["concept:name"] for e in trace["events"] if "concept:name" in e]
        for i in range(len(events) - 1):
            transitions[events[i]][events[i + 1]] += 1

    per_activity = {}
    weighted_sum = 0.0
    total_weight = 0

    for activity, successors in transitions.items():
        n = len(successors)
        total = sum(successors.values())
        if n <= 1:
            per_activity[activity] = 0.0
        else:
            raw = -sum((c / total) * math.log2(c / total) for c in successors.values())
            per_activity[activity] = raw / math.log2(n)
        weighted_sum += per_activity[activity] * total
        total_weight += total

    weighted_avg = weighted_sum / total_weight if total_weight > 0 else 0.0
    return per_activity, weighted_avg


def extract_traces(log_path):
    log = xes_importer.apply(
        log_path,
        parameters={"show_progress_bar": False}
    )

    result = []
    activities = set()
    traces_with_duplicates = 0

    trace_lengths = []  # NEW

    for trace in log:
        trace_info = {
            "trace_attributes": dict(trace.attributes),
            "events": []
        }

        timestamp_counts = defaultdict(int)

        for event in trace:
            event_dict = dict(event)
            trace_info["events"].append(event_dict)

            if "concept:name" in event_dict:
                activities.add(event_dict["concept:name"])

            if "time:timestamp" in event_dict:
                ts = event_dict["time:timestamp"]
                timestamp_counts[ts] += 1

        # ---- NEW: trace size ----
        trace_length = len(trace)
        trace_lengths.append(trace_length)

        duplicates = [ts for ts, count in timestamp_counts.items() if count > 1]
        if duplicates:
            traces_with_duplicates += 1

        result.append(trace_info)

    return result, activities, traces_with_duplicates, trace_lengths

def _process_single_file_wrapper(file_path):
    try:
        traces, activities, duplicated_count, trace_lengths = extract_traces(file_path)

        _, transition_entropy = compute_transition_entropy(traces)

        return {
            "file": os.path.basename(file_path),
            "total_traces": len(traces),
            "traces_with_duplicates": duplicated_count,
            "transition_entropy": transition_entropy,
            "num_activities": len(activities),

            # NEW METRICS
            "mean_trace_size": sum(trace_lengths) / len(trace_lengths) if trace_lengths else 0,
            "max_trace_size": max(trace_lengths) if trace_lengths else 0,
            "min_trace_size": min(trace_lengths) if trace_lengths else 0,
        }

    except Exception as e:
        return {
            "file": os.path.basename(file_path),
            "error": str(e)
        }


def analyze_xes_folder_parallel(folder_path, max_workers=None):
    """
    Recursively scan a folder for .xes files and analyze them in parallel,
    using multiprocessing.Pool + tqdm progress bar.

    Parameters:
        folder_path (str): Root directory to search
        max_workers (int, optional): Number of processes

    Returns:
        list of dict: analysis results per file
    """

    xes_files = []

    # Collect all .xes file paths
    for root, _, files in os.walk(folder_path):
        for file in files:
            if file.lower().endswith(".xes") or file.lower().endswith(".xes.gz"):
                xes_files.append(os.path.join(root, file))

    num_cores = max_workers or (os.cpu_count() or 1)

    # Parallel processing with progress bar
    with multiprocessing.Pool(num_cores) as pool:
        results = list(
            tqdm(
                pool.imap(_process_single_file_wrapper, xes_files),
                total=len(xes_files),
                desc="Processing XES files",
                unit="file"
            )
        )

    return results

def summarize_duplicates_text(results):
    """
    Print a textual summary of duplicated timestamps per file and overall.

    Parameters:
        results (list of dict): Output from analyze_xes_folder_parallel
    """

    # Filter out files with errors
    valid_results = [r for r in results if "error" not in r]

    if not valid_results:
        print("No valid results to summarize.")
        return

    files_with_duplicates_count = 0

    for r in valid_results:
        total_traces = r["total_traces"]
        duplicated_traces = r["traces_with_duplicates"]
        pct = (duplicated_traces / total_traces * 100) if total_traces > 0 else 0

        if duplicated_traces > 0:
            files_with_duplicates_count += 1

        print(
            f"Event Log: {r['file']}, "
            f"total traces: {total_traces}, "
            f"Traces with shared ts: {duplicated_traces}, "
            f"percentage: {pct:.1f}%, "
            f"Transition entropy: {r['transition_entropy']:.4f}, "
            f"Num activities: {r['num_activities']}, "
            f"Mean trace size: {r['mean_trace_size']:.2f}, "
            f"Min: {r['min_trace_size']}, "
            f"Max: {r['max_trace_size']}"
        )

    total_files = len(valid_results)
    print(f"\n{files_with_duplicates_count} out of {total_files} event logs have trace with duplicated timestamps.")

In [3]:
path = "all_event_logs"
results = analyze_xes_folder_parallel(path,22)
import pandas as pd

df = pd.DataFrame(results)
df["multiple_ts_percentage"] = (df["traces_with_duplicates"] / df["total_traces"]).round(2)
df["transition_entropy"] = df.transition_entropy.round(2)
df[["file","total_traces","num_activities","transition_entropy","multiple_ts_percentage"]].sort_values(by="file")

Processing XES files: 100%|███████████████████████████████████████████████| 24/24 [02:43<00:00,  6.82s/file]

,file,total_traces,num_activities,transition_entropy,multiple_ts_percentage
0,BPI Challenge 2017.xes.gz,31509,26,0.40,0.00
5,BPI Challenge 2018.xes.gz,43809,41,0.40,1.00
12,BPIC15_1.xes,1199,398,0.58,0.98
13,BPIC15_2.xes,832,410,0.62,0.99
7,BPIC15_3.xes,1409,383,0.54,0.98
19,BPIC15_4.xes,1053,356,0.58,0.99
10,BPIC15_5.xes,1156,389,0.59,1.00
2,BPI_Challenge_2012.xes.gz,13087,24,0.46,0.38
3,BPI_Challenge_2012_A.xes.gz,13087,10,0.48,0.17
8,BPI_Challenge_2012_O.xes.gz,5015,7,0.50,0.27
1,BPI_Challenge_2012_W.xes.gz,9658,7,0.52,0.00
6,BPI_Challenge_2013_closed_problems.xes.gz,1487,4,0.68,0.00
22,BPI_Challenge_2013_incidents.xes.gz,7554,4,0.70,0.00
9,BPI_Challenge_2013_open_problems.xes.gz,819,3,0.89,0.00
17,BPI_Challenge_2019.xes,251734,42,0.37,0.08
16,DomesticDeclarations.xes.gz,10500,17,0.23,0.00
15,Hospital_Billing.xes.gz,100000,18,0.19,0.00
20,Hospital_log.xes.gz,1143,624,0.43,0.99
18,InternationalDeclarations.xes.gz,6449,34,0.28,0.06
23,PermitLog.xes.gz,7065,51,0.30,0.13
4,PrepaidTravelCost.xes.gz,2099,29,0.29,0.03
14,RequestForPayment.xes.gz,6886,19,0.21,0.00
21,Road_Traffic_Fine_Management_Process.xes.gz,150370,11,0.33,0.06
11,Sepsis.xes.gz,1050,16,0.55,0.96

In [2]:
path = "baselines/next_activity_prediction/event_logs"
results = analyze_xes_folder_parallel(path,22)
import pandas as pd

df = pd.DataFrame(results)
df["multiple_ts_percentage"] = (df["traces_with_duplicates"] / df["total_traces"]).round(2)
df["transition_entropy"] = df.transition_entropy.round(2)
df[["file","total_traces","num_activities","transition_entropy","multiple_ts_percentage"]].sort_values(by="file")

Processing XES files: 100%|███████████████████| 16/16 [00:41<00:00,  2.60s/file]

,file,total_traces,num_activities,transition_entropy,multiple_ts_percentage
0,BPI Challenge 2017.xes.gz,31509,26,0.40,0.00
8,BPIC15_1.xes,1199,398,0.58,0.98
9,BPIC15_2.xes,832,410,0.62,0.99
4,BPIC15_3.xes,1409,383,0.54,0.98
14,BPIC15_4.xes,1053,356,0.58,0.99
6,BPIC15_5.xes,1156,389,0.59,1.00
2,BPI_Challenge_2012_A.xes.gz,13087,10,0.48,0.17
5,BPI_Challenge_2012_O.xes.gz,5015,7,0.50,0.27
1,BPI_Challenge_2012_W.xes.gz,9658,7,0.52,0.00
12,DomesticDeclarations.xes.gz,10500,17,0.23,0.00
11,Hospital_Billing.xes.gz,100000,18,0.19,0.00
13,InternationalDeclarations.xes.gz,6449,34,0.28,0.06
3,PrepaidTravelCost.xes.gz,2099,29,0.29,0.03
10,RequestForPayment.xes.gz,6886,19,0.21,0.00
15,Road_Traffic_Fine_Management_Process.xes.gz,150370,11,0.33,0.06
7,Sepsis.xes.gz,1050,16,0.55,0.96

In [3]:
df = pd.DataFrame(results)

df["multiple_ts_percentage"] = (df["traces_with_duplicates"] / df["total_traces"]).round(2)
df["transition_entropy"] = df.transition_entropy.round(2)

df[[
    "file",
    "total_traces",
    "num_activities",
    "transition_entropy",
    "multiple_ts_percentage",
    "mean_trace_size",
    "min_trace_size",
    "max_trace_size"
]].sort_values(by="file")

,file,total_traces,num_activities,transition_entropy,multiple_ts_percentage,mean_trace_size,min_trace_size,max_trace_size
0,BPI Challenge 2017.xes.gz,31509,26,0.40,0.00,38.156305,10,180
8,BPIC15_1.xes,1199,398,0.58,0.98,43.550459,2,101
9,BPIC15_2.xes,832,410,0.62,0.99,53.310096,1,132
4,BPIC15_3.xes,1409,383,0.54,0.98,42.356991,3,124
14,BPIC15_4.xes,1053,356,0.58,0.99,44.912631,1,116
6,BPIC15_5.xes,1156,389,0.59,1.00,51.109862,5,154
2,BPI_Challenge_2012_A.xes.gz,13087,10,0.48,0.17,4.649576,3,8
5,BPI_Challenge_2012_O.xes.gz,5015,7,0.50,0.27,6.230110,3,30
1,BPI_Challenge_2012_W.xes.gz,9658,7,0.52,0.00,17.613067,2,156
12,DomesticDeclarations.xes.gz,10500,17,0.23,0.00,5.374952,1,24
11,Hospital_Billing.xes.gz,100000,18,0.19,0.00,4.513590,1,217
13,InternationalDeclarations.xes.gz,6449,34,0.28,0.06,11.187936,3,27
3,PrepaidTravelCost.xes.gz,2099,29,0.29,0.03,8.692711,1,21
10,RequestForPayment.xes.gz,6886,19,0.21,0.00,5.343596,1,20
15,Road_Traffic_Fine_Management_Process.xes.gz,150370,11,0.33,0.06,3.733923,2,20
7,Sepsis.xes.gz,1050,16,0.55,0.96,14.489524,3,185